services:
  db:
    image: mysql:8
    container_name: mysql_grafana
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grafana_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  node_app:
    build: .
    container_name: node_api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: grafana_db
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["node", "server.js"]

volumes:
  db_data:
  grafana_data:
